apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosec-gateway
  labels:
    app: cosec-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosec-gateway
  template:
    metadata:
      labels:
        app: cosec-gateway
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - env:
            - name: LANG
              value: C.utf8
            - name: SPRING_DATA_REDIS_CLUSTER_NODES
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: nodes
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: SPRING_DATA_REDIS_CLUSTER_MAX_REDIRECTS
              value: "3"
            - name: TZ
              value: Asia/Shanghai
          image: registry.cn-shanghai.aliyuncs.com/ahoo/cosec-gateway:2.0.1
          startupProbe:
            httpGet:
              port: http
              path: /actuator/health
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
          name: cosec-gateway
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 2816Mi
            requests:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
            - mountPath: /opt/cosec-gateway-server/config/
              name: cosec-gateway-config
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: volume-localtime
        - configMap:
            name: cosec-gateway-config
          name: cosec-gateway-config