apiVersion: v1
kind: ConfigMap
metadata:
  name: cosec-gateway-config
  labels:
    app: cosec-gateway-config
data:
  bootstrap.yaml: |-
    spring:
      application:
        name: ${service.name:cosec-gateway}
  application.yaml: |-
    server:
      port: 8080
      error:
        whitelabel:
          enabled: false
    spring:
      cloud:
        gateway:
          server:
            webflux:
              globalcors:
                cors-configurations:
                  '[/**]':
                    allowed-origins: "*"
                    allowed-methods: "*"
                    allowed-headers: "*"
                    exposed-headers: "*"
                    max-age: 1800000
              default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
              routes:
                - id: cosec-auth
                  uri: lb://cosec-auth
                  predicates:
                    - Path=/cosec-auth/**
                  filters:
                    - StripPrefix=1
    cosec:
      authentication:
        enabled: false
      jwt:
        algorithm: hmac256
        secret: FyN0Igd80Gas8stTavArGKOYnS9uLWGA_
      ip2region:
        enabled: false
      authorization:
        local-policy:
          enabled: true
          init-repository: true
        cache:
          policy:
            maximum-size: 100000
          role:
            maximum-size: 100000

    logging:
      level:
        root: info
        me.ahoo.cosec.authorization.SimpleAuthorization: debug
