apiVersion: v1
kind: Service
metadata:
  name: cosec-gateway
  labels:
    app: cosec-gateway
spec:
  selector:
    app: cosec-gateway
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080