@startuml
!include layout.puml
title OAuth Flow

actor User
participant OAuthClientAuthentication
participant OAuthClientManager
participant OAuthClient
participant AuthorizationServer
participant OAuthClientPrincipalConverter
participant TokenConverter
User++

User -> OAuthClientAuthentication++: authorize()
OAuthClientAuthentication -> OAuthClientManager++: getOAuthClient()
OAuthClientAuthentication <-- OAuthClientManager--: OAuthClient
OAuthClientAuthentication -> OAuthClient++: authorize()
OAuthClientAuthentication <-- OAuthClient--: authorizeUrl
User <-- OAuthClientAuthentication--: authorizeUrl
User -> AuthorizationServer++: redirect : Authorization Grant
User <-- AuthorizationServer--: (Authorization code,state)
User -> OAuthClientAuthentication++: callback(code,state)
OAuthClientAuthentication -> OAuthClientManager++: getOAuthClient()
OAuthClientAuthentication <-- OAuthClientManager--: OAuthClient
OAuthClientAuthentication -> OAuthClient++: authenticate()
OAuthClient-> AuthorizationServer++: getAccessToken()
OAuthClient <-- AuthorizationServer--: accessToken
OAuthClient -> AuthorizationServer++: getUserInfo()
OAuthClient <-- AuthorizationServer--: userInfo
OAuthClientAuthentication <-- OAuthClient--: userInfo
OAuthClientAuthentication -> OAuthClientPrincipalConverter++: convert()
OAuthClientAuthentication <-- OAuthClientPrincipalConverter--: Principal
OAuthClientAuthentication -> TokenConverter++: convert()
OAuthClientAuthentication <-- TokenConverter--: token
User <-- OAuthClientAuthentication--: token
@enduml
