@startuml
!include layout.puml
title OAuth Flow

actor User
participant OAuthAuthentication
participant OAuthProviderManager
participant OAuthProvider
participant AuthorizationServer
participant OAuthUserPrincipalConverter
participant TokenConverter
User++

User -> OAuthAuthentication++: authorize()
OAuthAuthentication -> OAuthProviderManager++: getOAuthProvider()
OAuthAuthentication <-- OAuthProviderManager--: OAuthProvider
OAuthAuthentication -> OAuthProvider++: authorize()
OAuthAuthentication <-- OAuthProvider--: authorizeUrl
User <-- OAuthAuthentication--: authorizeUrl
User -> AuthorizationServer++: redirect : Authorization Grant
User <-- AuthorizationServer--: (Authorization code,state)
User -> OAuthAuthentication++: callback(code,state)
OAuthAuthentication -> OAuthProviderManager++: getOAuthProvider()
OAuthAuthentication <-- OAuthProviderManager--: OAuthProvider
OAuthAuthentication -> OAuthProvider++: authenticate()
OAuthProvider-> AuthorizationServer++: getAccessToken()
OAuthProvider <-- AuthorizationServer--: accessToken
OAuthProvider -> AuthorizationServer++: getUserInfo()
OAuthProvider <-- AuthorizationServer--: userInfo
OAuthAuthentication <-- OAuthProvider--: userInfo
OAuthAuthentication -> OAuthUserPrincipalConverter++: convert()
OAuthAuthentication <-- OAuthUserPrincipalConverter--: Principal
OAuthAuthentication -> TokenConverter++: convert()
OAuthAuthentication <-- TokenConverter--: token
User <-- OAuthAuthentication--: token
@enduml
