server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 1800000
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: cosec-auth
          uri: lb://cosec-auth
          predicates:
            - Path=/cosec-auth/**
          filters:
            - StripPrefix=1
        - id: google
          uri: https://www.google.com
          predicates:
            - Path=/google/**
          filters:
            - StripPrefix=1
cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  generator:
    enabled: true

cosec:
  authentication:
    enabled: false
  jwt:
    algorithm: hmac256
    secret: FyN0Igd80Gas8stTavArGKOYnS9uLWGA_
  ip2region:
    enabled: false
logging:
  level:
    root: info
    me.ahoo.cosec.authorization.SimpleAuthorization: debug
