server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 1800000
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: cosec-auth
          uri: lb://cosec-auth
          predicates:
            - Path=/cosec-auth/**
          filters:
            - StripPrefix=1
        - id: google
          uri: https://www.google.com
          predicates:
            - Path=/google/**
          filters:
            - StripPrefix=1

cosec:
  authentication:
    enabled: false
  jwt:
    algorithm: hmac256
    secret: FyN0Igd80Gas8stTavArGKOYnS9uLWGA_
  ip2region:
    enabled: false
  authorization:
    local-policy:
      enabled: true
      paths: classpath:build-in-policy
logging:
  level:
    root: info
    me.ahoo.cosec.authorization.SimpleAuthorization: debug
