apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosec-gateway
  labels:
    app: cosec-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosec-gateway
  template:
    metadata:
      labels:
        app: cosec-gateway
    spec:
      containers:
        - env:
            - name: SPRING_REDIS_HOST
              value: redis-uri:6379
            - name: SPRING_REDIS_PASSWORD
              value: redis-pwd
            - name: SPRING_CLOUD_COSKY_NAMESPACE
              value: '{dev}'
            - name: TZ
              value: Asia/Shanghai
          image: ahoowang/cosec-gateway:lastVersion
          startupProbe:
            httpGet:
              port: http
              path: /actuator/health
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
          name: cosec-gateway
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 2816Mi
            requests:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: volume-localtime
---
apiVersion: v1
kind: Service
metadata:
  name: cosec-gateway
  labels:
    app: cosec-gateway
spec:
  selector:
    app: cosec-gateway
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cosec-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cosec-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 600